package com.btb.odj.model;

import jakarta.persistence.Entity;
import jakarta.persistence.ManyToOne;

/**
 * CREATE TABLE driver
 *   (driver_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 *    name      VARCHAR2(255) NOT NULL UNIQUE,
 *    points    INTEGER NOT NULL,
 *    team_id   INTEGER,
 *    CONSTRAINT driver_pk PRIMARY KEY(driver_id),
 *    CONSTRAINT driver_fk FOREIGN KEY(team_id) REFERENCES team(team_id));
 */
@Entity
public class Driver extends AbstractEntity {

    private int points;

    @ManyToOne
    private Team team;
}
