services:

  db:
    image: gvenzl/oracle-free
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: RACE
      APP_USER_PASSWORD: RACE
    ports:
      - "1521:1521"

  mq:
    image: quay.io/artemiscloud/activemq-artemis-broker:artemis.2.28.0
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      AMQ_USER: CNL
      AMQ_PASSWORD: CNL
      AMQ_EXTRA_ARGS: "--relax-jolokia --require-login"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongo:/data/db

  mongo-gui:
    container_name: mongo-gui
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    restart: unless-stopped

  es:
    image: elasticsearch:8.11.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
