services:

  race:
    image: ghcr.io/markwigmans/race-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@db:1521/freepdb1"
      SPRING_ELASTICSEARCH_URIS: "http://es:9200"
      SPRING_ARTEMIS_BROKER-URL: "tcp://mq:61616"
      SPRING_DATA_MONGODB_URI: "mongodb://mongo/test"

  db:
    image: container-registry.oracle.com/database/free:latest
    volumes:
      - ./src/main/sql/startup:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: oracle
    ports:
      - "1521:1521"

  mq:
    image: quay.io/artemiscloud/activemq-artemis-broker:artemis.2.31.2
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      AMQ_USER: CNL
      AMQ_PASSWORD: CNL
      AMQ_EXTRA_ARGS: "--relax-jolokia --require-login"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongo:/data/db

  mongo-gui:
    container_name: mongo-gui
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    restart: unless-stopped

  es:
    image: elasticsearch:8.11.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false