services:
  dev-db:
    image: ghcr.io/markwigmans/23cfree
    environment:
      ORACLE_PWD: oracle
    ports:
      - 1521:1521
      - 5500:5500
      - 8080:8080
      - 8443:8443
      - 27017:27017