package com.btb.odj.model.jpa;

import jakarta.persistence.Entity;

/**
 *   (team_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
 *    name    VARCHAR2(255) NOT NULL UNIQUE,
 *    points  INTEGER NOT NULL,
 *    CONSTRAINT team_pk PRIMARY KEY(team_id));
 */
@Entity
public class Team extends AbstractEntity {

    private String name;
    private int points;
}
