services:
  dev-db:
    image: container-registry.oracle.com/database/free:latest
    volumes:
      - ./db/startup:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: oracle
    ports:
      - 1521:1521

  ords:
    image: container-registry.oracle.com/database/ords:latest
    volumes:
      - ./data/ords/variables:/opt/oracle/variables
      - ./data/ords/config/:/etc/ords/config/
    ports:
      - 8181:8181
      - 27017:27017
    depends_on:
      dev-db:
        condition: service_healthy