name: Build branch

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run formatter
        run: mvn -B process-sources -P formatter
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Commit formatting changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.email "noreply@github.com"
          git config user.name "The Builder"
          git add .
          git commit -m "committed formatting changes"
          git push

      - name: Build with Maven
        run: mvn -B package
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
