name: Release application

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: race-backend
  IMAGE_TAG: 1.0

jobs:
  deploy:
    name: Publish to github registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'

      - id: repository_owner
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}

      - name: Build with Maven
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml install -U -P docker,github -Ddocker.repo=${{ env.REGISTRY }}/${{ steps.repository_owner.outputs.lowercase }} -Ddocker.app.tag=${{ env.IMAGE_TAG }} -Ddocker.app.build.tag=${{ env.BUILD_NUMBER }}
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker image
        run: docker push -a ${{ env.REGISTRY }}/${{ steps.repository_owner.outputs.lowercase }}/${{ env.IMAGE_NAME }}
